// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vblalbrnmbrlrzedwbsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZibGFsYnJubWJybHJ6ZWR3YnN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMTIyMjUsImV4cCI6MjA1NDc4ODIyNX0.hAFOjQsWAGOAw88-vzOI8tlCatPtm-JpyFTnhW-VZ60";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);